export {default} from './client'
export * from './client'
export * from './middleware'
export {default as bearerAuth} from './middlewares/bearer-auth'
export {default as blob} from './middlewares/blob'
export {default as form} from './middlewares/form'
export {default as headers} from './middlewares/headers'
export {default as html} from './middlewares/html'
export {default as json} from './middlewares/json'